name: "Cloudflare Deployment"

on:
  workflow_run:
    workflows: ["CodeQL"]
    types: [completed]

jobs:
  deployment:
    runs-on: ${{ matrix.os }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: ğŸ“¥ Install Github Action Checkout
        uses: actions/checkout@v2

      - name: ğŸ“¥ Install NodeJS and Yarn
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: ğŸ”¨ Build Project
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build

      - name: "âš™ï¸ Configure Cloudfare Worker Server"
        run: |
          sudo cp server.mjs .next/server.mjs
          sudo sed -i 's/{"type": "commonjs"}/{"type": "commonjs","private": true,"main": "server.mjs"}/g' .next/package.json

      - name: ğŸ“¤ Publish to Cloudflare
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
